### ISSUE TITLE
No module named 'music.pymusic'

### ISSUE THREAD

**Issue by NarinderBrar** [INCF/MUSIC#69]
Hello, I am facing a problem with pymusic, while testing MUSIC/pymusic/examples. While MUSIC/examples working fine. 

Following is my environment detail.
OS: Ubuntu 20.04.1 LTS
Python 3.8.5
Cython 0.29.21
Open MPI 4.0.3
MUSIC 1.1.16

Error after running hello world example. 

narinder@narinder-desktop:~/Documents/MUSIC/pymusic/examples$ mpirun -np 4 music helloworld.music 
Traceback (most recent call last):
  File "./senders.py", line 3, in <module>
    import music
  File "/usr/local/lib/python3.8/dist-packages/music/__init__.py", line 26, in <module>
    from .pymusic import *
ModuleNotFoundError: No module named 'music.pymusic'
Traceback (most recent call last):
  File "./receivers.py", line 3, in <module>
    import music
  File "/usr/local/lib/python3.8/dist-packages/music/__init__.py", line 26, in <module>
    from .pymusic import *
ModuleNotFoundError: No module named 'music.pymusic'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "./senders.py", line 3, in <module>
    import music
  File "/usr/local/lib/python3.8/dist-packages/music/__init__.py", line 26, in <module>
    from .pymusic import *
ModuleNotFoundError: No module named 'music.pymusic'
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[49895,1],0]
  Exit code:    1

Also attached log of make install.
[log_make_install.txt](https://github.com/INCF/MUSIC/files/5747944/log_make_install.txt)

Please check if I missed something. 
Thanks

**Comment by techaakritisha** [comment]
@NarinderBrar I wanna work on this issue
